version = 1

[[annotations]]
path = ".python-version"
SPDX-FileCopyrightText = "2025 Maximilian Wenzkowski"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "uv.lock"
SPDX-FileCopyrightText = "2025 Maximilian Wenzkowski"
SPDX-License-Identifier = "CC0-1.0"
